// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgh2JYFjuG64uPu4l5PAFZE2E005jCGvQ',
    appId: '1:309952689430:web:7035ee40f52bd8d7e9cc37',
    messagingSenderId: '309952689430',
    projectId: 'pearlpro-d5fb8',
    authDomain: 'pearlpro-d5fb8.firebaseapp.com',
    storageBucket: 'pearlpro-d5fb8.appspot.com',
    measurementId: 'G-G99HD86VGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa0dOqlbK5GMbONobFFc6r1tH11GXyck4',
    appId: '1:309952689430:android:8f36328ee0f5830be9cc37',
    messagingSenderId: '309952689430',
    projectId: 'pearlpro-d5fb8',
    storageBucket: 'pearlpro-d5fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE8GblXqD3AU9MzdYAmYd-WBHbuy95fA4',
    appId: '1:309952689430:ios:39b2a0c8121fa95de9cc37',
    messagingSenderId: '309952689430',
    projectId: 'pearlpro-d5fb8',
    storageBucket: 'pearlpro-d5fb8.appspot.com',
    iosBundleId: 'com.example.pearl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE8GblXqD3AU9MzdYAmYd-WBHbuy95fA4',
    appId: '1:309952689430:ios:b9613274ccbf38b3e9cc37',
    messagingSenderId: '309952689430',
    projectId: 'pearlpro-d5fb8',
    storageBucket: 'pearlpro-d5fb8.appspot.com',
    iosBundleId: 'com.example.pearl.RunnerTests',
  );
}
